# Generated by Django 5.1 on 2024-08-20 21:35

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tx_name', max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_updated', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tx_name', max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_updated', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tx_name', max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_updated', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_column='tx_username', max_length=64, unique=True, verbose_name='Nome de Usuário')),
                ('password', models.CharField(db_column='tx_password', max_length=104, verbose_name='Senha')),
                ('name', models.CharField(blank=True, db_column='tx_name', max_length=256, null=True, verbose_name='Nome Completo')),
                ('email', models.CharField(blank=True, db_column='tx_email', max_length=256, null=True, verbose_name='E-mail')),
                ('last_login', models.DateTimeField(db_column='dt_last_login', null=True, verbose_name='Último Login')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Ativo')),
                ('is_superuser', models.BooleanField(db_column='cs_superuser', default=False, verbose_name='Superusuário')),
                ('is_staff', models.BooleanField(db_column='cs_staff', default=False, verbose_name='Membro da Equipe')),
                ('is_default', models.BooleanField(db_column='cs_default', default=False, verbose_name='Padrão')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'auth_user',
                'ordering': ['username'],
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='tx_title', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description')),
                ('serie_number', models.CharField(blank=True, db_column='tx_serie_number', max_length=200, null=True, verbose_name='Serie Number')),
                ('cost_price', models.DecimalField(db_column='nu_cost_price', decimal_places=2, max_digits=20, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(db_column='nu_selling_price', decimal_places=2, max_digits=20, verbose_name='Selling Price')),
                ('quantity', models.IntegerField(db_column='nu_quantity', default=0, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_updated', verbose_name='Updated at')),
                ('brand', models.ForeignKey(db_column='id_brand', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='nu_quantity', verbose_name='Quantity')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_updated', verbose_name='Updated at')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='core.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Outflow',
                'verbose_name_plural': 'Outflows',
                'db_table': 'outflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='nu_quantity', verbose_name='Quantity')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_updated', verbose_name='Updated at')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='core.product', verbose_name='Product')),
                ('supplier', models.ForeignKey(db_column='id_supplier', on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='core.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Inflow',
                'verbose_name_plural': 'Inflows',
                'db_table': 'inflow',
                'ordering': ['-created_at'],
            },
        ),
    ]
