# Generated by Django 5.1 on 2024-08-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='core.product', verbose_name='Product'),
        ),
    ]
